### ISSUE TITLE
Google Trusted Site Plugin - Validation Error

### ISSUE THREAD

**Issue by elenasem** [numinix/google_trusted_stores#1]
Hello, I installed the plugin - https://www.numinix.com/plugins/zen-cart-plugins/marketing/google-trusted-stores

But I keep getting validation error on the order confirmation page - Google Shopping Item ID is missing
And also, I don't see any option to purchase protection.

Zen cart version: 1.5.1
http://www.russiancombat.com

**Comment by jefflew** [comment]
This means the plugin hasn't been installed correctly and your Google Merchant Center data hasn't been added to the config.  

Please note: we're moving our bug reporting system to bitbucket.org.
